- name: Variable in ansible
  hosts: all
  #This is play level variables , map
  vars:
    cource: devops
    trainer: siva
    duration: 100hrs

  tasks:
    - name: printing variables
      ansible.builtin.debug:
        msg: "Hello im learning {{cource}}, Trainer is {{trainer}}"