- name: variables from files
  hosts: localhost #managing the ansible server itself
  vars_files:
  - variables.yml
  tasks:
  - name: printing variables
    ansible.builtin.debug:
      msg: "Im learning {{NAME}},TRAINER IS {{TRAINER}}"

