- name: Demo on vars at task level
  hosts: localhost
#  these are parent or play level variables
  vars:
    money: 20000
    houses: 2
  tasks:
    - name: printing variable from play
      ansible.builtin.debug:
        msg: "money is {{money}} , houses are {{houses}}"

    - name: printing variable from task and override
      vars:
        money: 30000 rupees
        land: 3 achers
      ansible.builtin.debug:
        msg: "money is {{money}} , land is {{land}} "