- name: Demo on vars at task level
  hosts: localhost
  vars:
    money: 20000
    houses: 2
  tasks:
    - name: printing variable from play
      ansible.builtin.debug:
        msg: "money is {{money}} , houses are {{houses}}"