- name: create user
  hosts: localhost
  tasks:
  - name: create roboshop user
    ansible.builtin.shell: id roboshop
    register: output
    ignore_errors: true

  - name: print command output
    ansible.builtin.debug:
      msg: output is {{output}}
  - name: print exit status
    ansible.builtin.debug:
      msg:  "{{output.rc}}"
