- name: create user
  hosts: localhost
  tasks:
  - name: check roboshop user exist or not
    ansible.builtin.shell: id roboshop
    register: output
    ignore_errors: true

  - name: print command output
    ansible.builtin.debug:
      msg: output is {{output}}
  - name: print exit status
    ansible.builtin.debug:
      msg:  "{{output.rc}}"
  - name: create roboshop user
    ansible.builtin.user:
     name: roboshop
    when: output.rc != 0
#     when output.rc not equal to zero then it means user does not exist then it will run