- name: demo on conditions example
  hosts: localhost
  tasks:
  - name: check directory is exist or not
    ansible.builtin.stat:
      path: /tmp/nandu
      register: st
      ignore_errors: true

  - name: print command output
    ansible.builtin.debug:
      msg: output is {{st}}


