- name: demo on conditions example
  hosts: localhost
  tasks:
  - name: check directory is exist or not
    ansible.builtin.stat:
      path: /tmp/nandu
    register: dir_to_check


  - name: directory found
    ansible.builtin.debug:
      msg: "directory /tmp is present"
    when: dir_to_check.stat.isdir is defined and dir_to_check.stat.isdir

