- name: demo on conditions example
  hosts: localhost
  tasks:
  - name: check directory is exist or not
    ansible.builtin.stat:
      path: /tmp/nandu
    register: dir_to_check


  - name: directory found
    ansible.builtin.debug:
      msg: "directory /tmp is present"
    when: dir_to_check.stat.isdir is defined and dir_to_check.stat.isdir

  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: /tmp/nandu
      state: directory
    when: not dir_to_check.stat.exists